# Generated by Django 5.2.4 on 2025-07-10 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmerLoan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='farmer',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='officer',
        ),
    ]
