# Generated by Django 4.2.23 on 2025-07-19 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_cooperative_id_user_national_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cooperative_id',
            field=models.CharField(blank=True, help_text='Required for cooperatives only!', max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Cooperative ID must be in format COOP-XXXX-XXXX', regex='^COOP-\\d{4}-\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(max_length=70, validators=[django.core.validators.RegexValidator(message='Full name must contain only letters and spaces', regex='^[A-Za-z ]+$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.IntegerField(blank=True, help_text='Required for farmers only!', max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='National ID must be 16 digits', regex='^\\d{7}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits starting with 07', regex='^07\\d{8}$')]),
        ),
    ]
