# Generated by Django 4.2.23 on 2025-07-23 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_cooperative_id_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, help_text='Required for farmers only!', max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='National ID must be 7 digits', regex='^\\d{7}$')]),
        ),
    ]
