# Generated by Django 5.2.4 on 2025-07-11 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_user_cooperative_id_user_national_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerWealth',
            fields=[
                ('farmer_wealth_id', models.AutoField(primary_key=True, serialize=False)),
                ('milk_quantity', models.CharField(max_length=100)),
                ('income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('farmer_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
