# Generated by Django 5.2.4 on 2025-07-11 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_document_farmer_id_document_file_url_and_more'),
        ('users', '0002_user_cooperative_id_user_national_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='farmer_id',
        ),
        migrations.AddField(
            model_name='document',
            name='user_id',
            field=models.ForeignKey(default=1, help_text='Stores the user’s unique identifier', on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
    ]
