# Generated by Django 5.2.4 on 2025-07-11 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='farmer_id',
            field=models.ForeignKey(default='001', help_text='Stores the user’s unique identifier', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='file_url',
            field=models.ImageField(default=1, help_text='Stores the URL of the file', upload_to='documents/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='document_id',
            field=models.AutoField(help_text="Stores the document's unique identifier", primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.TextField(help_text='Stores the document type, credit report, or loan agreement', max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Stores the time the document was uploaded'),
        ),
    ]
