# Generated by Django 5.2.3 on 2025-06-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_url',
            field=models.ImageField(default='https://www.two-rivers.org/sites/default/files/fileattachments/inspections_zoning_and_planning/page/4991/loan-application-letter.pdf', upload_to='documents/'),
            preserve_default=False,
        ),
    ]
