# Generated by Django 5.2.4 on 2025-07-03 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_document_file_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file_url',
        ),
    ]
