# Generated by Django 5.2.4 on 2025-07-11 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_repayments', '0002_alter_loanrepayment_user'),
        ('users', '0002_user_cooperative_id_user_national_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrepayment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
