
# Generated by Django 5.2.3 on 2025-06-22 11:20

from django.db import migrations, models

# Generated by Django 4.2.23 on 2025-06-24 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

# Generated by Django 5.2.3 on 2025-06-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperative',
            fields=[
                ('officer_id', models.AutoField(primary_key=True, serialize=False)),
                ('officer_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),

                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),

            ],
        ),
    ]
