# Generated by Django 4.2.23 on 2025-06-25 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0002_cooperative_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooperative',
            name='user',
        ),
    ]
