# Generated by Django 4.2.23 on 2025-06-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0003_remove_cooperative_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperative',
            name='password',
            field=models.CharField(default='@XYZ456', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
