# Generated by Django 5.2.4 on 2025-08-05 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankpartners', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooperativepartnerbank',
            name='amount_disbursed',
        ),
    ]
