<<<<<<< HEAD
# Generated by Django 5.2.3 on 2025-06-22 11:24
=======
<<<<<<< HEAD
# Generated by Django 5.2.3 on 2025-06-22 11:20
=======
<<<<<<< HEAD
# Generated by Django 4.2.23 on 2025-06-23 03:45
=======
# Generated by Django 5.2.3 on 2025-06-22 12:45
>>>>>>> 0deec2764997999f18229389ea37de61606ba027
>>>>>>> 4f0891618da362996c36835b56698068c12abe0c
>>>>>>> 912d69cbe90a8446810f79fbccc9ec87649ed5a6

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
<<<<<<< HEAD
=======
<<<<<<< HEAD
=======
        
>>>>>>> 0deec2764997999f18229389ea37de61606ba027
>>>>>>> 4f0891618da362996c36835b56698068c12abe0c
>>>>>>> 912d69cbe90a8446810f79fbccc9ec87649ed5a6
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('farmer_id', models.AutoField(primary_key=True, serialize=False)),
                ('join_date', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
