# Generated by Django 4.2.23 on 2025-06-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=70)),
                ('phone_number', models.CharField(max_length=70)),
                ('password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('type', models.CharField(choices=[('farmer', 'Farmer'), ('cooperative', 'Cooperative')], max_length=20)),
            ],
        ),
    ]
