# Generated by Django 5.2.4 on 2025-08-05 12:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerWealth',
            fields=[
                ('farmer_wealth_id', models.AutoField(primary_key=True, serialize=False)),
                ('milk_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('livestock_number', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
            ],
        ),
    ]
