# Generated by Django 5.2.3 on 2025-06-20 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerWealth',
            fields=[
                ('farmer_wealth_id', models.AutoField(primary_key=True, serialize=False)),
                ('milk_quantity', models.CharField(max_length=100)),
                ('income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.farmer')),
            ],
        ),
    ]
