<<<<<<< HEAD
# Generated by Django 5.2.3 on 2025-06-20 14:58

import django.db.models.deletion
from django.db import migrations, models
=======
<<<<<<< HEAD
# Generated by Django 5.2.3 on 2025-06-22 11:20

import django.db.models.deletion
from django.db import migrations, models
=======
<<<<<<< HEAD
# Generated by Django 4.2.23 on 2025-06-23 03:45

from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 5.2.3 on 2025-06-22 12:46

import django.db.models.deletion
from django.db import migrations, models
>>>>>>> 0deec2764997999f18229389ea37de61606ba027
>>>>>>> 4f0891618da362996c36835b56698068c12abe0c
>>>>>>> 912d69cbe90a8446810f79fbccc9ec87649ed5a6


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmer', '0001_initial'),
        ('farmerLoan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('loan_repayment_id', models.AutoField(primary_key=True, serialize=False)),
                ('due_date', models.DateTimeField()),
                ('amount_remaining', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.TextField()),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.farmer')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmerLoan.loan')),
            ],
        ),
    ]
