# Generated by Django 5.2.4 on 2025-07-03 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_repayments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_repayment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='loan_repayments.loanrepayment')),
            ],
        ),
    ]
