# Generated by Django 5.2.4 on 2025-07-10 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_repayments', '0002_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanrepayment',
            name='farmer',
        ),
    ]
