# Generated by Django 5.2.4 on 2025-07-10 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_repayments', '0003_remove_loanrepayment_farmer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
